/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5eb1455f82f82d390e7843ec
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";
import Chip from "@material-ui/core/Chip";
import Input from "@material-ui/core/Input";

// Custom Actions


// START IMPORT ACTIONS
import AdminActions from "../redux/actions/AdminActions";
import EmployeActions from "../redux/actions/EmployeActions";
import ClientActions from "../redux/actions/ClientActions";

// END IMPORT ACTIONS

/** APIs

* actionsAdmin.create
*	@description CRUD ACTION create
*
* actionsAdmin.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsAdmin.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsEmploye.findByadmin
*	@description CRUD ACTION findByadmin
*	@param Objectid key - Id of model to search for
*
* actionsClient.list
*	@description CRUD ACTION list
*
* actionsEmploye.list
*	@description CRUD ACTION list
*
* actionsClient.findBypayment
*	@description CRUD ACTION findBypayment
*	@param Objectid key - Id of model to search for
*

**/

class AdminEdit extends Component {
  // Init admin
  constructor(props) {
    super(props);
    this.state = {
      admin: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsAdmin.loadAdmin(this.props.match.params.id);
      this.props.actionsEmploye.findByadmin(this.props.match.params.id);
      this.props.actionsClient.findBypayment(this.props.match.params.id);
    }
    
    this.props.actionsClient.loadClientList();
    this.props.actionsEmploye.loadEmployeList();
  }

  // Insert props admin in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      admin: props.admin
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.admin._id) {
      this.props.actionsAdmin.saveAdmin(this.state.admin).then(data => {
        this.props.history.push("/admins/");
      });
    } else {
      this.props.actionsAdmin.createAdmin(this.state.admin).then(data => {
        this.props.history.push("/admins/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Admin Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="Name"
            label="Name"
            value={this.state.admin.Name || ""}
            onChange={Utils.handleChange.bind(this, "admin")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.admin.Name && this.state.admin.Name === ""
              ? { error: true }
              : {})}
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation m:m payment with Client */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="payment">Payment</InputLabel>
            <Select
              multiple
              value={this.state.admin.payment || []}
              onChange={Utils.handleChangeSelect.bind(this, "admin")}
              input={<Input id="payment" name="payment" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listClient && this.props.listClient.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.admin.payment &&
                      this.state.admin.payment.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* Relation m:m sallery with Employe */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="sallery">Sallery</InputLabel>
            <Select
              multiple
              value={this.state.admin.sallery || []}
              onChange={Utils.handleChangeSelect.bind(this, "admin")}
              input={<Input id="sallery" name="sallery" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listEmploye && this.props.listEmploye.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.admin.sallery &&
                      this.state.admin.sallery.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with Employe */}
          
          <h3>Employe</h3>
          {(!this.props.listEmploye || this.props.listEmploye.length === 0) && 
            <div>No Employe associated</div>
          }
          {this.props.listEmploye &&
            this.props.listEmploye.map((item, i) => {
              return (
                <Link to={"/employes/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with Client */}
          
          <h3>Client</h3>
          {(!this.props.listClient || this.props.listClient.length === 0) && 
            <div>No Client associated</div>
          }
          {this.props.listClient &&
            this.props.listClient.map((item, i) => {
              return (
                <Link to={"/clients/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/admins/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsAdmin: bindActionCreators(AdminActions, dispatch),
    actionsEmploye: bindActionCreators(EmployeActions, dispatch),
    actionsClient: bindActionCreators(ClientActions, dispatch),
  };
};

// Validate types
AdminEdit.propTypes = { 
  actionsAdmin: PropTypes.object.isRequired,
  actionsEmploye: PropTypes.object.isRequired,
  actionsClient: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    admin: state.AdminEditReducer.admin,
    listClient: state.AdminEditReducer.listClient,
    listEmploye: state.AdminEditReducer.listEmploye,
    listEmploye: state.AdminEditReducer.listEmploye,
    listClient: state.AdminEditReducer.listClient
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(AdminEdit);
