/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5eb1455f82f82d390e7843ec
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import { DateTimePicker } from "material-ui-pickers";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";

// Custom Actions


// START IMPORT ACTIONS
import EmployeActions from "../redux/actions/EmployeActions";
import ClientActions from "../redux/actions/ClientActions";
import AdminActions from "../redux/actions/AdminActions";

// END IMPORT ACTIONS

/** APIs

* actionsEmploye.create
*	@description CRUD ACTION create
*
* actionsEmploye.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsEmploye.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsClient.list
*	@description CRUD ACTION list
*
* actionsAdmin.list
*	@description CRUD ACTION list
*
* actionsAdmin.findBysallery
*	@description CRUD ACTION findBysallery
*	@param Objectid key - Id of model to search for
*
* actionsClient.findByproject
*	@description CRUD ACTION findByproject
*	@param Objectid key - Id of model to search for
*

**/

class EmployeEdit extends Component {
  // Init employe
  constructor(props) {
    super(props);
    this.state = {
      employe: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsEmploye.loadEmploye(this.props.match.params.id);
      this.props.actionsClient.findByproject(this.props.match.params.id);
      this.props.actionsAdmin.findBysallery(this.props.match.params.id);
    }
    
    this.props.actionsAdmin.loadAdminList();
    this.props.actionsClient.loadClientList();
  }

  // Insert props employe in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      employe: props.employe
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.employe._id) {
      this.props.actionsEmploye.saveEmploye(this.state.employe).then(data => {
        this.props.history.push("/employes/");
      });
    } else {
      this.props.actionsEmploye.createEmploye(this.state.employe).then(data => {
        this.props.history.push("/employes/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Employe Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="Name"
            label="Name"
            value={this.state.employe.Name || ""}
            onChange={Utils.handleChange.bind(this, "employe")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.employe.Name && this.state.employe.Name === ""
              ? { error: true }
              : {})}
          />
          
          
          <TextField
            id="Surname"
            label="Surname"
            value={this.state.employe.Surname || ""}
            onChange={Utils.handleChange.bind(this, "employe")}
            margin="normal"
            fullWidth
          />
          
          <DateTimePicker
            id="dob"
            label="Dob"
            className="mt-20 mb-20"
            ampm={false}
            value={
              this.state.employe.dob
                ? new Date(this.state.employe.dob)
                : null
            }
            onChange={Utils.handleChangeDate.bind(this, "employe", "dob")}
            fullWidth
            autoOk
            disableFuture
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m admin with Admin */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="admin">
              Admin
            </InputLabel>
            <Select
              value={this.state.employe.admin || ""}
              onChange={Utils.handleChangeSelect.bind(this, "employe")}
              inputProps={{
                id: "admin",
                name: "admin"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listAdmin && this.props.listAdmin.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* Relation 1:m project with Client */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="project">
              Project
            </InputLabel>
            <Select
              value={this.state.employe.project || ""}
              onChange={Utils.handleChangeSelect.bind(this, "employe")}
              inputProps={{
                id: "project",
                name: "project"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listClient && this.props.listClient.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with Client */}
          
          <h3>Client</h3>
          {(!this.props.listClient || this.props.listClient.length === 0) && 
            <div>No Client associated</div>
          }
          {this.props.listClient &&
            this.props.listClient.map((item, i) => {
              return (
                <Link to={"/clients/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with Admin */}
          
          <h3>Admin</h3>
          {(!this.props.listAdmin || this.props.listAdmin.length === 0) && 
            <div>No Admin associated</div>
          }
          {this.props.listAdmin &&
            this.props.listAdmin.map((item, i) => {
              return (
                <Link to={"/admins/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/employes/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsEmploye: bindActionCreators(EmployeActions, dispatch),
    actionsClient: bindActionCreators(ClientActions, dispatch),
    actionsAdmin: bindActionCreators(AdminActions, dispatch),
  };
};

// Validate types
EmployeEdit.propTypes = { 
  actionsEmploye: PropTypes.object.isRequired,
  actionsClient: PropTypes.object.isRequired,
  actionsAdmin: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    employe: state.EmployeEditReducer.employe,
    listAdmin: state.EmployeEditReducer.listAdmin,
    listClient: state.EmployeEditReducer.listClient,
    listClient: state.EmployeEditReducer.listClient,
    listAdmin: state.EmployeEditReducer.listAdmin
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(EmployeEdit);
