/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5eb1455f82f82d390e7843ec
*
* You will get 10% discount for each one of your friends
* 
*/

// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// ADMIN
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const FINDBYPAYMENT_ADMIN_SUCCESS = "FINDBYPAYMENT_ADMIN_SUCCESS";
export const FINDBYSALLERY_ADMIN_SUCCESS = "FINDBYSALLERY_ADMIN_SUCCESS";
export const GET_ADMIN_SUCCESS = "GET_ADMIN_SUCCESS";
export const LIST_ADMIN_SUCCESS = "LIST_ADMIN_SUCCESS";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";

// CLIENT
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const FINDBYPAYMENT_CLIENT_SUCCESS = "FINDBYPAYMENT_CLIENT_SUCCESS";
export const FINDBYPROJECT_CLIENT_SUCCESS = "FINDBYPROJECT_CLIENT_SUCCESS";
export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
export const LIST_CLIENT_SUCCESS = "LIST_CLIENT_SUCCESS";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";

// EMPLOYE
export const CREATE_EMPLOYE_SUCCESS = "CREATE_EMPLOYE_SUCCESS";
export const DELETE_EMPLOYE_SUCCESS = "DELETE_EMPLOYE_SUCCESS";
export const FINDBYADMIN_EMPLOYE_SUCCESS = "FINDBYADMIN_EMPLOYE_SUCCESS";
export const FINDBYPROJECT_EMPLOYE_SUCCESS = "FINDBYPROJECT_EMPLOYE_SUCCESS";
export const GET_EMPLOYE_SUCCESS = "GET_EMPLOYE_SUCCESS";
export const LIST_EMPLOYE_SUCCESS = "LIST_EMPLOYE_SUCCESS";
export const UPDATE_EMPLOYE_SUCCESS = "UPDATE_EMPLOYE_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
